### ISSUE TITLE
PDOS is not complete

### ISSUE THREAD

**Issue by akentphonon** [SMTG-UCL/ThermoPlotter#48]
Dear developers,

Thank you for the great code.  I have been using it for past few days - and stumbled upon something curious.

For my test case a certain section of PDOS is missing:

As you  will see in the figure below the DoS around 13 THz is missing. When I manually plot DoS it seems fine. 
Could this be a bug?

Man thanks for your time

best,
Alex

![Screenshot from 2022-12-08 21-47-30](https://user-images.githubusercontent.com/59974303/206564250-5d8bef7f-bcf1-4ef6-9532-65837ee8b4f0.png)

**Comment by akentphonon** [comment]
The issue comes from 

n = int(np.ceil(0.9*len(f))) in  add_dos function as it does it find the correct ends. Changing it to 1.1 works for me.

**Comment by kbspooner** [comment]
Hi Alex,

Thanks for finding and diagnosing this bug! It is now fixed in the latest version on the master branch. I'm glad you're finding it useful!

Thanks,
Kieran
